[project]
name = "oj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "dotenv>=0.9.9",
    "google-genai>=1.27.0",
    "markdown>=3.8.2",
]
