# Generated by Django 5.2.4 on 2025-07-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input',
            new_name='input_data',
        ),
    ]
