# Generated by Django 5.2.4 on 2025-07-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_input_testcase_input_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='is_complete',
        ),
    ]
