databases:
  - name: OJ_Database
    databaseName: oj_database
    user: oj_database_user

services:
  - type: web
    name: oj-web
    env: docker
    plan: free
    dockerfilePath: oj/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: OJ_Database
          property: connectionString