# Generated by Django 5.2.4 on 2025-07-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_no',
        ),
    ]
