# Generated by Django 5.2.4 on 2025-07-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
