name: Docker Image CI

on:
  push:
     branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --pull --rm -f oj/Dockerfile -t vaibhavkumar10/ojproject:latest oj

      - name: Push Docker image
        run: docker push vaibhavkumar10/ojproject:latest
      
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
