name: Build Docker Image CI

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . OJ/oj/ -f ./oj/Dockerfile -t oj:latest
