name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --pull --rm -f 'oj\Dockerfile' -t 'vaibhavkumar10/ojproject:latest' 'oj'
    - name: |
      run : docker image push vaibhavkumar10/ojproject:latest 
